[package]
name = "harrison_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.6.0"
log = "0.4.17"
env_logger = "0.9.0"
itertools = "0.10.1"
priority-queue = "1.3.0"
dhat = "0.3.2"

[profile.release]
debug = 1

[features]
dhat-heap = []    
