[package]
name = "harrison_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = "0.22.0"
logos = "0.15.0"
regex = "1.6.0"
env_logger = "0.9.0"
itertools = "0.10.1"
priority-queue = "1.3.0"

[build-dependencies]
lalrpop = "0.22.0"
