
name: harrison-rust build, check, test, and lint
on: 
  push:
    branches:    
    - '*'

jobs:
  build-and-check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - uses: actions/checkout@v2

      # Install
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      # Compile 
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      # Test 
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      # Format 
      - name: Run rust fmt 
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      # Clippy 
      - name: Run rust clippy 
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings
